package com.cognizant.orm_learn.repository;

import com.cognizant.orm_learn.model.Country;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
 * NationDataAccess - Data access layer for Country entities
 * Extends JpaRepository to provide standard CRUD operations
 * for geographical territory management in the system
 */
@Repository
public interface CountryRepository extends JpaRepository<Country, String> {
    // Repository methods are automatically generated by Spring Data JPA
}